# Generated by Django 2.0.3 on 2018-03-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя бага')),
                ('description', models.TextField(verbose_name='Описание бага')),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя фичи')),
                ('description', models.TextField(verbose_name='Описание фичи')),
                ('is_release', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.TextField(verbose_name='Тестовый случай')),
                ('expected_behavior', models.TextField(verbose_name='Ожидаемое поведение')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Feature', verbose_name='Связная фича')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.Project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='bug',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Feature', verbose_name='Связная фича'),
        ),
    ]
