# Generated by Django 2.0.3 on 2018-04-02 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='created_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 4, 2, 19, 41, 19, 899201, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='created_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 4, 2, 19, 41, 34, 99994, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='planned_time',
            field=models.FloatField(default=0.0, verbose_name='Планируемое время в часах'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 4, 2, 19, 42, 6, 826066, tzinfo=utc), verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='created_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 4, 2, 19, 42, 16, 335637, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
