# Generated by Django 2.0.3 on 2018-04-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180424_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('IW', 'In work'), ('RW', 'Ready for a review'), ('C', 'Canceled'), ('E', 'Completed')], default='N', max_length=2, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
